{{- if gt .Values.scale.maxReplicas '1' }}
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  annotations:
  name: {{ .Release.Name }}
spec:
  minReplicas: {{ .Values.scale.minReplicas }}
  maxReplicas: {{ .Values.scale.maxReplicas }}
  metrics:
    {{- if .Values.scale.memoryThresholdPercentage -}}
    - resource:
        name: memory
        targetAverageUtilization: {{ .Values.scale.memoryThresholdPercentage }}
      type: Resource
    {{- end -}}
    {{- if .Values.scale.cpuThresholdPercentage -}}
    - resource:
        name: cpu
        targetAverageUtilization: {{ .Values.scale.cpuThresholdPercentage }}
      type: Resource
    {{- end -}}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Release.Name }}
{{- end }}