{{- if gt .Values.scale.minReplicas 1.0 }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ .Release.Name }}
spec:
  minAvailable: {{ .Values.scale.minAvailable }}
  selector:
    matchLabels:
      type: {{ .Chart.Name }}
      app: {{ .Release.Name }}
{{- end }}
