# To deploy an app with hpa. resources.requests are mandatory for the hpa to work
image_repo: jmalloc/echo-server
image_tag: "0.3.6"
service:
  name: medium
port: 8080
resources:
  requests:
    cpu: 0.5
    memory: 256Mi
  limits:
    memory: 1Gi
