name: Lint and Test Charts

on: push

env:
  HELM_VERSION: v3.8.1

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: ${{ env.HELM_VERSION }}

      - uses: actions/setup-python@v5
        with:
          python-version: 3.7

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.6.1

      - name: Run chart-testing (lint)
        run: ct lint --chart-dirs . --charts .

  template-test:
    needs: [lint-test]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        file:
          - name: ci/values-empty.yaml
          - name: ci/values-minimal.yaml
          - name: ci/values-complete.yaml
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: ${{ env.HELM_VERSION }}

      - name: Run chart-testing (template) on different YAML files
        run: helm template --dry-run --generate-name . -f "${{ matrix.file.name }}"

  kubeval-chart:
    runs-on: ubuntu-latest
    needs:
      - lint-test
      - lint-template-test
    strategy:
      matrix:
        k8s:
          # from https://github.com/yannh/kubernetes-json-schema
          - v1.28.9
          - v1.29.4
          # - v1.30.0
    steps:
      - name: Checkout
        uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4.1.3
        with:
          fetch-depth: 0

      - name: Run kubeval
        env:
          KUBERNETES_VERSION: ${{ matrix.k8s }}
        run: .github/kubeval.sh
