name: Lint and Test Charts

on: push

env:
  HELM_VERSION: v3.8.1

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: ${{ env.HELM_VERSION }}

      - uses: actions/setup-python@v5
        with:
          python-version: 3.7

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.6.1

      - name: Run chart-testing (lint)
        run: ct lint --chart-dirs . --charts .

  template-test:
    needs: [lint-test]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        file:
          - name: ci/values-empty.yaml
          - name: ci/values-minimal.yaml
          - name: ci/values-complete.yaml
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: ${{ env.HELM_VERSION }}

      - name: Run chart-testing (template) on different YAML files
        run: helm template --dry-run --generate-name . -f "${{ matrix.file.name }}"
